version: '3.8'

services:
  logging_server:
    build:
      context: ./logging_server
    container_name: logging_server
    ports:
      - "6000:6000"
    

  server1:
    build:
      context: ./server1
    container_name: server1
    ports:
      - "5001:5001"
    depends_on:
      - logging_server

  server2:
    build:
      context: ./server2
    container_name: server2
    ports:
      - "5002:5002"
    depends_on:
      - logging_server

  gui_client:
    build:
      context: ./client/gui
    container_name: gui_client
    depends_on:
      - server1
      - server2
      - logging_server
    # For GUI display support
    environment:
      - DISPLAY=:0
      - XAUTHORITY=/home/nyathi/.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/nyathi/.Xauthority:/home/nyathi/.Xauthority:rw
    privileged: true #allow extra privileges to the container
    network_mode: "host"